spring:
  application:
    name: cambio-service  datasource:    url: jdbc:mysql://localhost:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:    url: jdbc:mysql://localhost:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    user: root
    password: admin123
  sleuth:
    sampler:
      probability: 1.0
server:  port: 8000
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs